# Generated by Django 5.1.2 on 2024-10-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='email',
            field=models.CharField(default='email@email.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='phone',
            field=models.CharField(default='123-123-1234', max_length=100),
            preserve_default=False,
        ),
    ]
