# Generated by Django 5.1.2 on 2024-10-31 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='status',
        ),
    ]
