# Generated by Django 5.1.2 on 2024-11-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_order_product_remove_order_quantity_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payer_name',
            field=models.CharField(default='Mike', max_length=100),
            preserve_default=False,
        ),
    ]
