# Generated by Django 5.1.2 on 2025-01-30 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_category_google_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
